# Generated by Django 5.1.6 on 2025-03-04 09:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_url_one_time_use_alter_url_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 11, 9, 40, 41, 388086, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="UrlVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 3, 4, 9, 40, 41, 388560, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="links.url",
                    ),
                ),
            ],
            options={
                "unique_together": {("url", "date", "ip_address")},
            },
        ),
    ]
