# Generated by Django 5.1.6 on 2025-03-04 11:54

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0004_alter_url_expires_at_urlvisit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 11, 11, 54, 56, 257120, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="urlvisit",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
