# Generated by Django 5.1.6 on 2025-04-03 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0005_alter_url_expires_at_alter_urlvisit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 10, 13, 17, 51, 928678, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="new_url",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
